<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsAotCompatible>true</IsAotCompatible></PropertyGroup>
  <ItemGroup>
    <Compile Include="Contracts.fs" />
    <Compile Include="SelectionPolicy.fs" />
    <ProjectReference Include="../ModConductor.ModLibrary/ModConductor.ModLibrary.fsproj" />
    <PackageReference Include="FSharp.Core" />
  </ItemGroup>
</Project>
