<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsAotCompatible>true</IsAotCompatible></PropertyGroup>
  <ItemGroup>
    <Compile Include="Activation.fs" />
    <Compile Include="StateLease.fs" />
    <Compile Include="WebLink.fs" />
    <ProjectReference Include="../ModConductor.Platform/ModConductor.Platform.fsproj" />
    <PackageReference Include="FSharp.Core" />
  </ItemGroup>
</Project>
