<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsAotCompatible>true</IsAotCompatible></PropertyGroup>
  <ItemGroup>
    <Compile Include="Contracts.fs" />
    <Compile Include="HttpTransfer.fs" />
    <Compile Include="DownloadSession.fs" />
    <ProjectReference Include="../ModConductor.ArtifactLibrary/ModConductor.ArtifactLibrary.fsproj" />
    <PackageReference Include="FSharp.Core" />
  </ItemGroup>
</Project>
