<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsAotCompatible>true</IsAotCompatible></PropertyGroup>
  <ItemGroup>
    <Compile Include="Contracts.fs" />
    <Compile Include="LinuxNative.fs" />
    <Compile Include="LinuxStore.fs" />
    <Compile Include="WindowsStore.fs" />
    <Compile Include="Session.fs" />
    <PackageReference Include="FSharp.Core" />
  </ItemGroup>
</Project>
