<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsAotCompatible>true</IsAotCompatible></PropertyGroup>
  <ItemGroup>
    <Compile Include="AssemblyInfo.fs" />
    <Compile Include="Contracts.fs" />
    <Compile Include="MigrationResult.fs" />
    <Compile Include="Direct.fs" />
    <Compile Include="ModOrganizerInput.fs" />
    <Compile Include="ModOrganizerSettings.fs" />
    <Compile Include="ModOrganizerMods.fs" />
    <Compile Include="ModOrganizerProfiles.fs" />
    <Compile Include="ModOrganizerDownloads.fs" />
    <Compile Include="ModOrganizer.fs" />
    <Compile Include="VortexSource.fs" />
    <Compile Include="VortexJson.fs" />
    <Compile Include="VortexProfiles.fs" />
    <Compile Include="VortexMods.fs" />
    <Compile Include="VortexOrder.fs" />
    <Compile Include="VortexDownloads.fs" />
    <Compile Include="Vortex.fs" />
    <ProjectReference Include="../ModConductor.Platform/ModConductor.Platform.fsproj" />
    <ProjectReference Include="../ModConductor.ModLibrary/ModConductor.ModLibrary.fsproj" />
    <ProjectReference Include="../ModConductor.ModSelection/ModConductor.ModSelection.fsproj" />
    <PackageReference Include="FSharp.Core" />
  </ItemGroup>
</Project>
