<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsAotCompatible>true</IsAotCompatible></PropertyGroup>
  <ItemGroup>
    <Compile Include="AssemblyInfo.fs" />
    <Compile Include="Contracts.fs" />
    <Compile Include="ModOrganizer.fs" />
    <ProjectReference Include="../ModConductor.Platform/ModConductor.Platform.fsproj" />
    <ProjectReference Include="../ModConductor.ModLibrary/ModConductor.ModLibrary.fsproj" />
    <ProjectReference Include="../ModConductor.ModSelection/ModConductor.ModSelection.fsproj" />
    <PackageReference Include="FSharp.Core" />
  </ItemGroup>
</Project>
