name: mod_conductor
description: Mod Conductor desktop application.
publish_to: none
resolution: workspace
version: 0.1.0+1

environment:
  sdk: 3.13.2
  flutter: 3.47.2

dependencies:
  mc_bethesda:
    path: ../../packages/mc_bethesda
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.20.3

  mc_desktop:
    path: ../../packages/mc_desktop
  mc_game_contexts:
    path: ../../packages/mc_game_contexts
  mc_skse:
    path: ../../packages/mc_skse

  mc_client:
    path: ../../packages/mc_client

  mc_credentials:
    path: ../../packages/mc_credentials
  mc_artifacts:
    path: ../../packages/mc_artifacts
  mc_migration:
    path: ../../packages/mc_migration
  mc_profile_data:
    path: ../../packages/mc_profile_data
  mc_executables:
    path: ../../packages/mc_executables
  mc_generated_outputs:
    path: ../../packages/mc_generated_outputs

  mc_file_plans:
    path: ../../packages/mc_file_plans
  mc_mod_library:
    path: ../../packages/mc_mod_library
  mc_workspaces:
    path: ../../packages/mc_workspaces

  mc_ui_foundation:
    path: ../../packages/mc_ui_foundation
  mc_ui_collections:
    path: ../../packages/mc_ui_collections

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  generate: true
  uses-material-design: true
