<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><IsAotCompatible>true</IsAotCompatible></PropertyGroup><ItemGroup><Compile Include="Contracts.fs"/><Compile Include="Discovery.fs"/></ItemGroup><ItemGroup><ProjectReference Include="../ModConductor.ArchiveInstallation/ModConductor.ArchiveInstallation.fsproj"/><PackageReference Include="FSharp.Core"/></ItemGroup></Project>
