part of 'app.dart';

CredentialPreferencesLabels _credentialLabels(AppLocalizations labels) =>
    CredentialPreferencesLabels(
      nexusMods: labels.credentialNexusMods,
      disconnectTitle: labels.credentialDisconnectTitle,
      disconnect: labels.credentialDisconnect,
      disconnectPause: labels.credentialDisconnectPause,
      disconnectRemovesSaved: labels.credentialDisconnectRemovesSaved,
      sessionOnlyTitle: labels.credentialSessionOnlyTitle,
      sessionOnly: labels.credentialSessionOnly,
      sessionOnlyLost: labels.credentialSessionOnlyLost,
      sessionOnlyKeepsSaved: labels.credentialSessionOnlyKeepsSaved,
      clearSessionTitle: labels.credentialClearSessionTitle,
      removeSavedTitle: labels.credentialRemoveSavedTitle,
      clearSignIn: labels.credentialClearSignIn,
      removeSignIn: labels.credentialRemoveSignIn,
      clearsSessionToo: labels.credentialClearsSessionToo,
      storageDetails: labels.credentialStorageDetails,
      close: labels.close,
      problem: (problem) => switch (problem) {
        CredentialProblem.locked => labels.credentialStorageLocked,
        CredentialProblem.unavailable => labels.credentialStorageUnavailable,
        CredentialProblem.denied => labels.credentialStorageDenied,
        CredentialProblem.timedOut => labels.credentialStorageTimedOut,
        CredentialProblem.cancelled => labels.credentialStorageCancelled,
        CredentialProblem.tooLarge => labels.credentialStorageTooLarge,
        CredentialProblem.failed => labels.credentialStorageFailed,
      },
      waitingSignIn: labels.credentialWaitingSignIn,
      premium: labels.credentialPremium,
      accountCurrent: labels.credentialAccountCurrent,
      checkingAccount: labels.credentialCheckingAccount,
      accountCheckFailed: labels.credentialAccountCheckFailed,
      notConnected: labels.credentialNotConnected,
      notSignedIn: labels.credentialNotSignedIn,
      notSaved: labels.credentialNotSaved,
      cancelSignIn: labels.credentialCancelSignIn,
      checkAccount: labels.credentialCheckAccount,
      signInAgain: labels.credentialSignInAgain,
      connect: labels.credentialConnect,
      signIn: labels.credentialSignIn,
      personalApiKey: labels.credentialPersonalApiKey,
      openApiKeySettings: labels.credentialOpenApiKeySettings,
      openApiKeySettingsFailed: labels.credentialOpenApiKeySettingsFailed,
      showPersonalApiKey: labels.credentialShowPersonalApiKey,
      hidePersonalApiKey: labels.credentialHidePersonalApiKey,
      submitPersonalApiKey: labels.credentialSubmitPersonalApiKey,
      storageCheckFailed: labels.credentialStorageCheckFailed,
      checkEngine: labels.credentialCheckEngine,
      savedNotRemoved: labels.credentialSavedNotRemoved,
      unlockKeyring: labels.credentialUnlockKeyring,
      saved: labels.credentialSaved,
      noneSaved: labels.credentialNoneSaved,
      cannotCheckSaved: labels.credentialCannotCheckSaved,
      newSignIns: labels.credentialNewSignIns,
      saveOnComputer: labels.credentialSaveOnComputer,
      checkStorage: labels.credentialCheckStorage,
      retryRemoval: labels.credentialRetryRemoval,
    );

NexusLinkPreferencesLabels _nexusLinkLabels(AppLocalizations labels) =>
    NexusLinkPreferencesLabels(
      title: labels.nexusLinks,
      description: labels.nexusOpenLinks,
      removeWindowsTitle: labels.nexusRemoveWindowsTitle,
      removeTitle: labels.nexusRemoveTitle,
      removeWindows: labels.nexusRemoveWindows,
      remove: labels.nexusRemove,
      chooseOtherDefault: labels.nexusChooseOtherDefault,
      restoreDefault: labels.nexusRestoreDefault,
      availableWindows: labels.nexusAvailableWindows,
      available: labels.nexusAvailable,
      notAddedWindows: labels.nexusNotAddedWindows,
      off: labels.nexusOff,
      cannotCheck: labels.nexusCannotCheck,
      defaultApp: labels.nexusDefaultApp,
      modConductor: labels.nexusModConductor,
      anotherApp: labels.nexusAnotherApp,
      notSet: labels.nexusNotSet,
      cannotCheckDefault: labels.nexusCannotCheckDefault,
      chooseDefaultWindows: labels.nexusChooseDefaultWindows,
      defaultChanged: labels.nexusDefaultChanged,
      checkFailed: labels.nexusCheckFailed,
      addWindows: labels.nexusAddWindows,
      useModConductor: labels.nexusUseModConductor,
      openWindows: labels.nexusOpenWindows,
      checkDefault: labels.nexusCheckDefault,
    );

String _appearanceLabel(AppLocalizations labels, AppearancePreference value) =>
    switch (value) {
      AppearancePreference.system => labels.systemAppearance,
      AppearancePreference.light => labels.light,
      AppearancePreference.dark => labels.dark,
    };

String _contrastLabel(AppLocalizations labels, ContrastPreference value) =>
    switch (value) {
      ContrastPreference.system => labels.systemContrast,
      ContrastPreference.standard => labels.standardContrast,
      ContrastPreference.high => labels.highContrast,
    };
