<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Core.Api" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="All" />
  </ItemGroup>
</Project>
