name: mod_conductor_ui
publish_to: none
environment:
  sdk: 3.13.2
workspace:
  - apps/mod_conductor
  - packages/mc_ui_foundation
  - packages/mc_client
  - packages/mc_workspaces
dev_dependencies:
  protoc_plugin: 25.0.0
