name: mod_conductor_ui
publish_to: none
environment:
  sdk: 3.13.2
workspace:
  - apps/mod_conductor
  - packages/mc_ui_foundation
  - packages/mc_client
  - packages/mc_game_contexts
  - packages/mc_workspaces
  - packages/mc_ui_collections
  - packages/mc_mod_library
  - packages/mc_file_plans
  - packages/mc_generated_outputs
  - packages/mc_executables
  - packages/mc_profile_data
  - packages/mc_credentials
  - packages/mc_artifacts
dev_dependencies:
  protoc_plugin: 25.0.0
