name: mc_mod_library
description: Installed mod and saved version presentation.
publish_to: none
resolution: workspace
version: 0.1.0
environment:
  sdk: 3.13.3
  flutter: 3.47.4
dependencies:
  flutter:
    sdk: flutter
  mc_ui_foundation:
    path: ../mc_ui_foundation
  mc_client:
    path: ../mc_client
  mc_ui_collections:
    path: ../mc_ui_collections
  file_selector: 1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
